### ISSUE TITLE
求证性询问

### ISSUE THREAD

**Issue by yxdy-yxkx** [kotori2/-llasww_master_db_diff#1]
原来隔壁的寄过。想了解下关于魔形娶粗，现在还能实现吗？

**Comment by kotori2** [comment]
错别字过多，无法理解

**Comment by yxdy-yxkx** [comment]
不好意思，当了一回谜语人。想了解下目前解密算法是用python编写的吗？

**Comment by kotori2** [comment]
https://github.com/esterTion/unity-texture-toolkit/blob/fcdc6fe3dbbc7073dc8a54ad3abaf855f05941c1/llas/main.php 
不过因为他用的metadata api不更新了，我用的自己的

**Comment by yxdy-yxkx** [comment]
可惜了，所有的模型产出停留在2020.5月。找到初始解好的包，我自己又整了几个。
原来我以前看过他的解密攻略，希望他这个api自己拉密钥还能用。

**Comment by yxdy-yxkx** [comment]
原来是用于检测更新数据，来预估游戏的更新内容。想岔了，以为能用来解包提取3D模型

**Comment by TunglinInamin** [comment]
3D模型要個別解包，這裡只能比較db來看新增/刪除了那些檔案

**Comment by kotori2** [comment]
> 原来是用于检测更新数据，来预估游戏的更新内容。想岔了，以为能用来解包提取3D模型

算法是一样的，key在db里面有，改改代码就行，只不过没有现成的轮子。
